### ISSUE TITLE
support for anchor elements in shadowRoot

### ISSUE THREAD

**Issue by bradrydzewski** [WebReflection/onpushstate#2]
I was doing a bit of testing with custom elements and shadowdom and noticed that click events return the root element in the shadow dom instead of the anchor, and as a result, are not handled by the `click` handler in this library.

It looks like one might be able to use the following logic:

```diff
- var target = e.target;
+ var target = e.target.shadowRoot ? e.path[0] : e.target;
  var closest = target.closest || function (A) {
    while (target && target.nodeName !== A) target = target.parentNode;
    return target;
  };
```

I do apologize for not being more proactive with a pull request, however, I consider myself a novice with many of these newer web technologies and was unsure this proposed fix would be fully compatible or capture all edge cases. I am happy to send a pull request, if you think this is the right approach.

**Comment by WebReflection** [comment]
> capture all edge cases

if the shadowRoot is closed mode, I'm afraid this change won't produce expected results.

However, your suggestion would be an improvement indeed.

**Comment by bradrydzewski** [comment]
thanks so much for the quick enhancement. much appreciated :)
