### ISSUE TITLE
traverse path for first anchor when inside shadow root

### ISSUE THREAD

**Issue by bradrydzewski** [WebReflection/onpushstate#3]
I came across another edge case when using webcomponents. I have the following bit of code inside a shadow dom:

```
<a href>
  <div>Some title</div>
  <svg><!--some icon-->
</a>
```

In the above example, when I click the anchor the target element is either the div or svg. Instead of using `path[0]` when the shadow root exists, I think we need to traverse the path to find the first anchor tag in the list. `[svg, a, document-fragment, custom-element, body, html, document, Window]`

I'm thinking something like this:

```diff
-var target = e.target.shadowRoot ? path[0] : e.target;
+var target = e.target.shadowRoot ? e.path.find(function(element){ return element.nodeName === 'A' }) : e.target;
```

It seems to solve the issue, but wanted to first get your thoughts. If you think this makes sense I can issue a pull request.

**Comment by bradrydzewski** [comment]
ok my suggested fix above was problematic because `e.path.find` could return an empty value and result in an exception. We would need to make sure target is not undefined:

```diff
-var anchor = (target.closest || function (A) {
+var anchor = (target && target.closest || function (A) {
```

**Comment by bradrydzewski** [comment]
Sorry for all the noise here. I enabled experimental customelement support in Firefox and it looks like we should use [`composedPath`](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) instead of `path`.

```diff
-var target = e.target.shadowRoot ? path[0] : e.target;
+var target = e.target.shadowRoot ? e.composedPath().find(function(element){ return element.nodeName === 'A' }) : e.target;
```

**Comment by WebReflection** [comment]
OK, first of all: apologies for ignoring this issue for so long, I've just realized it exists now.

Secondly, I'd like to have an example to test against, so that I can fix the issue properly.

I am not sure if your proposed solution works in all cases, so a proper help that currently fails would be ideal.

Thanks.

**Comment by WebReflection** [comment]
as nothing happened ever, I'll close this.
