### ISSUE TITLE
What's the logic for preventing default for same-origin link?

### ISSUE THREAD

**Issue by dy** [WebReflection/onpushstate#4]
I have links to different pages in project
```html
<a href="/clients.html">Clients</a>
<a href="/users.html">Users</a>
```
If `onpushstate` is imported, it prevents navigation by clicking on links. Is that intended behavior?
Intuitively `onpushstate` must enable `pushstate` event, not prevent default interaction.

**Comment by WebReflection** [comment]
![Screenshot from 2019-12-16 19-20-30](https://user-images.githubusercontent.com/85749/70932126-46b96000-2039-11ea-9177-4838de948309.png)

**Comment by WebReflection** [comment]
> If onpushstate is imported, it prevents navigation by clicking on links. Is that intended behavior?

it's the only thing this library does: if you click a link you have a pushstate event and **you** need to handle that.

if you don't want this behavior, I'm afraid you picked the wrong library, as it was born to do exactly that and nothing else.

**Comment by dy** [comment]
Not sure I understand. Why instead of creating harmless `pushstate` event and let user decide if default behavior should be prevented or not, as `popstate` event does, this library overrides default behavior, makes links broken?

**Comment by WebReflection** [comment]
you cannot have a `pushstate` event without pushing the state, and if you _pushState_, hence you have the event, the behavior is the expected one.

The [documentation](https://webreflection.github.io/onpushstate/#doc) explains what's this library goal, and it's not going to change, as it makes no sense to emit events about things that maybe never happened, and overwriting the `history.pushState` without being sure developers would pass the right arguments is both obtrusive, and error prone.

Best Regards.

**Comment by dy** [comment]
> you need to handle that.

I intended to enhance `useQueryParam` hook as 

https://github.com/unihooks/unihooks/blob/7a984340f6173eaee249b6d9a24365fa7e9eb2d1/src/useQueryParam.js#L52-L53

so that would rerender whenever history changes this or the other way (`pushstate` or `popstate`).
Some libs intercept standard `<a>` clicks to trigger router in not-destructive way.
I guess that's the wrong choice then.

**Comment by WebReflection** [comment]
you don't need this library to intercept clicks, but any library that triggers a `pushstate` event without this actually happened is doing something wrong.

If you want to handle navigation though, give [a-route](https://github.com/WebReflection/a-route#readme) a chance.

P.S. I don't understand why you are OK with `popstate` behavior, which is a page that changed URL without changing the content, but you're not OK with `pushstate` which does exactly the same thing: it changes the URL without changing the page.

**Comment by WebReflection** [comment]
Last thoughts: if you want the browser to actually surf the new page, the whole logic would break. However, you can also `location.href = event.state` within the event notification, if needed.

**Comment by dy** [comment]
I just mistook lib's logic for [that answer](https://stackoverflow.com/a/4585031/1052640). There seems to be no reliable way to detect `pushstate`.

**Comment by WebReflection** [comment]
I've already said you can be obtrusive and replace the original pushState, but then again, the pushState event **means** pushState is happening. I think you're a bit confused about what you're looking for exactly, or at least I don't understand. The pushState replaces the URL without loading the page. Your router should do something when such event is triggered, otherwise you change page and goodbye running JS.

**Comment by dy** [comment]
You're right, I had to obtrusively replace `pushState`. Must not be serious penalty, will look for consequences. Observing links click makes sense only in router component, supposing it prevents default indeed.
Anyways, here's implementation https://github.com/unihooks/unihooks/blob/master/src/useQueryParam.js#L96-L141
