### ISSUE TITLE
<a> without href error

### ISSUE THREAD

**Issue by dy** [WebReflection/onpushstate#5]
Navigating to link without href `<a>go</a>` gives error
```sh
index.js:39 Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at HTMLDocument.<anonymous> (index.js:39)
```

**Comment by WebReflection** [comment]
and what are you expecting to navigate without href ?

**Comment by dy** [comment]
Not having an error, just as regular links do.

**Comment by WebReflection** [comment]
but regular links ... _link_ to something, right? I might fix this, but I don't understand the use case.

**Comment by WebReflection** [comment]
Fixed anyway 👋

**Comment by dy** [comment]
`<a>` can be used in markup as semantic/visual tag, eg. as button with link visual style, but without navigation action, eg. showing popup.

**Comment by WebReflection** [comment]
my rule of thumbs:
  * if it links somewhere, it's a link
  * if it doesn't link somewhere, it's a button (or any other thing that is not a link)

**Comment by dy** [comment]
> If the a element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant.

https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element

**Comment by WebReflection** [comment]
the whole GitHub follows my rule of thumbs though, and I've never used empty `<a>` in 20 years ... but hey, I also don't care, and since W3C is happy, then use empty `<a>` as much as you like 🎉
